version: '3'
services:
  web:
    #image: mywordpress:1.0
    build: .
    ports:
      - "80"
    depends_on:
      - redis
    networks:
      - mynetwork
  redis:
    image: redis
    networks:
      - mynetwork

networks:
  mynetwork:
